gunmode: debug               # 开发模式, debug, release, test
addr: :8888                  # HTTP绑定端口
name: apiserver              # API Server的名字...
log:
    writers: file,stdout
    logger_level: DEBUG
    logger_file: log/apiserver.log
    log_format_text: false
    rollingPolicy: size
    log_rotate_date: 1
    log_rotate_size: 1024
    log_backup_count: 7
